#!/bin/bash


###STAR analysis


### number of reads in FASTQ file

wc -l ENCFF000EWJ.fastq/4
## 117876320
wc -l ENCFF000EXE.fastq/4
##131831897 
wc -l ENCFF000EZF.fastq/4
##95520094
wc -l ENCFF000EZH.fastq/4
##127696795
wc -l ENCFF000FCG.fastq/4
##128402941
wc -l ENCFF000FCH.fastq/4
##116517502
wc -l ENCFF001RCX.fastq/4
##141170272
wc -l ENCFF001RCY.fastq/4
##246085152

total number of reads = 1105100973

mean = 138137622

### number of reads mapped to genome

samtools view -c -F 260 -f 2 sample.bam

ewj_ewx.bam - 139935216
eww_exe.bam - 247847712
ezf_ezt.bam - 181516430
ezr_ezh.bam - 240995456
fcg_fci.bam - 236916396
fch_fcu.bam- 214685016
rcx_rdf.bam - 245165834
rcy_rdg.bam - 84651148

total number of mapped reads =  1591713208

avg value of mapped reads = 198964151

###number of reads mapped to transcriptome

#583418846

###kallisto performs mapping to transcriptome 

#count number of transcripts in kallisto abundance.tsv with expression values > 0

##168079

###number of different genes identified

##60676 

