#!/bin/bash


## nanopore analysis 

###number of reads in FASTQ file

###FASTQ file contains 4 lines pertaining to one read so count all lines and divide by 4 gives number of fastq reads

wc -l NA12878-DirectRNA_All_Guppy_3.2.6.fastq/4 = 13361612

###number of mapped reads to genome

###flag 2324 throws away the unmapped and secondary alignments

###mapping to genome produces sam file which is then converted to bam file

samtools view genome.sam -bh -t -F 2324 Homo_sapiens.GRCh38.dna.primary_assembly.fa > genome.filt.bam

samtools view -c genome.filt.bam

###5336687

###number of reads mapped to transcriptome

samtools view rna.sam -bh -t -F 2324 Homo_sapiens.GRCh38.dna.primary_assembly.fa > rna.filt.bam

samtools view -c rna.filt.bam

##9390854


###number of different transcripts identified 

###count number of transcripts with expression values > 0

###60021

###number of different genes identified

### using biomaRt package associate genes for all the transcripts corresponding to each gene thereby counting unique genes

##18295









